# Generated by Django 3.2.20 on 2025-03-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsing", "0006_alter_dataupdatesettings_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupdatesettings",
            name="max_allowed_term",
            field=models.CharField(
                choices=[("Spring", "Spring"), ("Fall", "Fall")],
                default="Fall",
                help_text="Select either Spring or Fall term",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dataupdatesettings",
            name="max_allowed_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name="dataupdatesettings",
            name="min_allowed_term",
            field=models.CharField(
                choices=[("Spring", "Spring"), ("Fall", "Fall")],
                default="Fall",
                help_text="Select either Spring or Fall term",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dataupdatesettings",
            name="min_allowed_year",
            field=models.IntegerField(default=2020),
        ),
    ]
